kind: pipeline
name : Kernel Compiler
version: rev1.5_template
steps:
 - name: Kernel Compilation
   image: xyzuan/xdocker:latest
   environment:
     ANYKERNEL:
       from_secret: ANYKERNEL
     TG_TOKEN:
       from_secret: TG_TOKEN
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     GITHUB_TOKEN:
       from_secret: GIT_TOKEN
   commands:
     - bash Source
     - bash Merlin
#     - rm -rf lamer/out AnyKernel
#     - sleep 10s
#     - bash Lancelot
